### ISSUE TITLE
精读《设计模式 - Visitor 访问者模式》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#306]
访问者模式。

---

[精读《设计模式 - Visitor 访问者模式》](https://github.com/ascoders/weekly/blob/v2/189.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Visitor%20%E8%AE%BF%E9%97%AE%E8%80%85%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by niaogege** [comment]
babel中插件机制用到了这种设计模式，就是 AST 和 visitor 分离，在 traverse（遍历）AST 的时候，调用注册的 **visitor** 来对其进行处理。
