### ISSUE TITLE
精读《DOM diff 原理详解》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#308]
本文综合 react 与 vue dom diff 原理，一次性把 dom diff 讲明白。

另外 Dom diff 并不是理论算法的 Dom diff，而是工业界的简化版，是综合考虑了时间空间复杂度是否能运用在生产环境后，特意进行的简化，因此其中还有不少工程智慧值得学习。

---

[精读《DOM diff 原理详解》](https://github.com/ascoders/weekly/blob/v2/190.%E7%B2%BE%E8%AF%BB%E3%80%8ADOM%20diff%20%E5%8E%9F%E7%90%86%E8%AF%A6%E8%A7%A3%E3%80%8B.md)

**Comment by baxtergu** [comment]
<img src="https://camo.githubusercontent.com/95ed1c3303d42560a3ce6e207699943a14806a3b65b1d9a1f587ce66e251e278/68747470733a2f2f696d672e616c6963646e2e636f6d2f696d6765787472612f69332f4f31434e303168466955673731754a706e5a7a436a47685f2121363030303030303030363031372d322d7470732d313433302d3538322e706e67">

这张图上的编号 `4` 是不是应该是编号 `3`

**Comment by ascoders** [comment]
没关系，DOM diff 是渲染层做的事，Fiber 是协调层做的事。

**Comment by zhangyunihao** [comment]
感谢回复  关于最长递增子序列为了获得最优解
dp(i) = num[i] > num[i - 1] ? dp(i - 1) + 1 : 1
这个状态转移方程是不对的，建议文中强调这里求的不是最优解
dp(i) = (max (dp[j]) || 0) +1，其中j<=i且num[i]<num[j]
但是这样复杂度就是O(n2)的
如果使用贪心法加上二分法，时间复杂度也要O(nlogn)
所以意思是说vue的diff算法的这一步没有用到最优解？

**Comment by zhangyunihao** [comment]
在这篇文章中，
[React 框架内部的运作可以分为 3 层：

Virtual DOM 层，描述页面长什么样。
Reconciler 层，负责调用组件生命周期方法，进行 Diff 运算等。
Renderer 层，根据不同的平台，渲染出相应的页面，比较常见的是 ReactDOM 和 ReactNative。]https://segmentfault.com/a/1190000018250127)

看起来进行diff运算也在Reconciler 层

**Comment by ascoders** [comment]
@zhangyunihao 这块是我写错啦，感谢提醒。应该说 最长递增**连续**子序列 的时间复杂度是 O(n)。vue 用的算法是找 最长递增子序列，而非 最长递增连**续子**序列，**因为连续子序列不一定是最优解**。我会尽快修正文章中描述错误的部分。

另外 Diff 在 React 中确实在 Reconciler 层做的，感谢指出。渲染层很薄，只用于做跨平台渲染，不负责做其他计算逻辑如 DOM diff。

**Comment by blinkcat** [comment]
看了一遍，关于计算节点移动的那块，不知道我的理解对不对。
vue为了找到最少的移动次数，额外花了o(nlgn)的时间找到那个最长连续子串，而react是直接在遍历的过程中计算出移动步骤，我看Angular也是用了和react类似的方法。那么vue的diff算法总体来说真的是o(n)吗？比方说一个长列表，打乱顺序后重新渲染。
