### ISSUE TITLE
精读《高性能表格》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#309]
笔者结合自身项目经历，总结做高性能表格的方法，实现以下效果：

1. 鼠标 or 拖滚动条滚动完全无白屏。
2. 行列与单元格跟随无延迟。
3. 可拓展，单元格可任意合并替换为可视化组件。

---

[精读《高性能表格》](https://github.com/ascoders/weekly/blob/v2/191.%E7%B2%BE%E8%AF%BB%E3%80%8A%E9%AB%98%E6%80%A7%E8%83%BD%E8%A1%A8%E6%A0%BC%E3%80%8B.md)

**Comment by shijiatongxue** [comment]
文章很赞👏，有两个疑问

1. 横轴只能纵向滚动是指？
2. 有demo吗？

**Comment by zhengao261** [comment]
文章很赞，我也刚用 DOM 实现了一个高性能的表格。 

可以实现表头固定和左右列固定

性能是同数据量 ElementUI 表格的3-5倍。且大数据量渲染之后，拖拽滚动无卡顿，无延迟。

实践总结了一下就是要想高性能，尽量少的使用事件监听。

为了提升性能使用了一些黑科技，刚加了学长微信，可以给黄大神提供一些不成熟的思路哈。

**Comment by ascoders** [comment]
@shijiatongxue 无 demo，内部产品不方便放出来，但效果是验证过的。

**Comment by jhoneybee** [comment]
我正在实现一个高性能的表格.  总结一下几点. 

1. 采用 react-window 来作虚拟滚动. 
2. 固定列, 采用 `position: absolute; float: right or left` . 一共三个表格
3. 合并列头部, 采用表格头部和body 分离, 那么只要计算出来宽度对其,那么就没有其他问题了.
4. 编辑表格 cell 在 click 的时候切换一下编辑器即可 ( 还在开发)

![Peek 2021-04-14 09-52](https://user-images.githubusercontent.com/24241052/114642869-32f23c80-9d07-11eb-95a5-d5fd388199ef.gif)

> PS: 不知道为什么 Linux 下录制会是这样的.

期间遇到的问题 

1. 有滚动条的时候, 滚动条会占用宽度, 最后动态生成不可见的div 来获取到滚动条的宽度
2. 头部合并的时候, 采用 flex 布局来进行自动居中. 头部是嵌套的. 
3. 最后一点, 其实非常重要, 数据驱动视图, 定义好表格的数据格式,.

**Comment by ascoders** [comment]
![short](https://user-images.githubusercontent.com/7970947/114861678-26add280-9e20-11eb-8300-6c280fba785a.gif)

下面是比较完整的，文件 10M，如果卡顿可能你本地没下载完。上图是1M大小的。

![666](https://user-images.githubusercontent.com/7970947/114861528-f6feca80-9e1f-11eb-94cb-1178effa2bbd.gif)

这个是笔者按照本文思路实现的效果，供参考。数据量123万单元格。

**Comment by jhoneybee** [comment]
> ![short](https://user-images.githubusercontent.com/7970947/114861678-26add280-9e20-11eb-8300-6c280fba785a.gif)
> 
> 下面是比较完整的，文件 10M，如果卡顿可能你本地没下载完。上图是1M大小的。
> 
> ![666](https://user-images.githubusercontent.com/7970947/114861528-f6feca80-9e1f-11eb-94cb-1178effa2bbd.gif)
> 
> 这个是笔者按照本文思路实现的效果，供参考。数据量123万单元格。

非常感谢大佬, 打算重新将 react-window 替换掉. 用模拟滚动.

**Comment by jhoneybee** [comment]
关于表格的滚动条同步问题,大致与一下有关 

- CSS will-change 属性
- Chrome 73 中的 `{passive: false}`

参照地址

- https://github.com/bvaughn/react-window/issues/221
- https://github.com/facebook/react/issues/14856

**Comment by ascoders** [comment]
@zenglinan 效果是这样，但实现没那么复杂。用 js 控制滚动自然就能实现该效果。

也可以做一种类比，假设用 canvas 绘制表格，那么你可以在滚动函数里实现渲染，滚动多少位移，就渲染多少位移的像素，只要按需渲染优化做得好，滚动就不会卡顿，然而渲染永远发生在滚动前，所以不可能出现白屏。

**Comment by daisybin** [comment]
@zhengao261 hello 你好 我在尝试实现这个table 遇到一些问题 想问一下是否可与你参考一下你的代码
