### ISSUE TITLE
精读《DOM diff 最长上升子序列》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#310]
本文介绍求最长上升子序列的三种做法，暴力 O(2ⁿ)、动态规划 O(n²)、非正常人类思维才能想到的贪婪二分 O(nlogn)。Vue DOM diff 正是采用了第三种方案实现的。

看完介绍后，你会发现时间复杂度上巧夺天工的算法，会导致最长上升子序列出现一个严重问题，即虽然长度正确，但内容可能是错误的，我们进一步看看 Vue 是如何修复队列内容的。

---

[精读《DOM diff 最长上升子序列》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/192.%E7%B2%BE%E8%AF%BB%E3%80%8ADOM%20diff%20%E6%9C%80%E9%95%BF%E4%B8%8A%E5%8D%87%E5%AD%90%E5%BA%8F%E5%88%97%E3%80%8B.md)

**Comment by stormqx** [comment]
> 本文介绍求最长上升子序列的三种做法，暴力 O(2ⁿ)、动态规划 O(n²)、非正常人类思维才能想到的贪婪二分 O(nlogn)。Vue DOM diff 正是采用了第三种方案实现的。
> 
> 看完介绍后，你会发现时间复杂度上巧夺天工的算法，会导致最长上升子序列出现一个严重问题，即虽然长度正确，但内容可能是错误的，我们进一步看看 Vue 是如何修复队列内容的。

怎么没看到文章在哪？

**Comment by ascoders** [comment]
@stormqx 下周一准时发布，open 时可以用来讨论～ 发布后会 close 掉并附上文章链接，也可以继续讨论。

**Comment by LoonLi** [comment]
感谢您的分享！但是阅读完之后有点疑问。
对于贪心-二分法的介绍中，并没有出现二分的部分，所介绍的“只要替换了最后一个或者插入的时候，栈顺序就是正确的”这个方法也似乎有点问题。
比方说，对于文章中的例子[3,7,22,4,8,13,9,11,12]来说，如果添加两个要素变成[3,7,22,4,8,13,,9,11,12,1,14]的话，按照保存最后一个替换的备份的方法，结果是变成[1,4,8,9,11,12,14]，而不是正确的[3,4,8,9,11,12,14]。而且每次操作最后一个要素时都备份的话，这个备份的时间也需要考虑到时间复杂度上，最终的时间复杂度会接近于O(n^2)。
根据其他资料的话是根据栈的结果二分查找每一个最接近的元素，那样的话复杂度确实是O(n + nlogn)。
也许是我的理解有问题，若有人能解答我的疑问的话非常感谢！

**Comment by ascoders** [comment]
@LoonLi  感谢提出质疑！原文算法确实有问题。

关于二分是没问题的。二分出现在 “查找栈中稍大元素” 的过程中，因为栈中元素单调递增，因此可以用二分法查找，再替换或插入。

关于正确序列，我写的算法是错误的，但是我稍后会给出一个正确算法。

**Comment by ascoders** [comment]
@LoonLi **原文已更新，以下是我给出的找出正确序列方案，如有问题欢迎继续指出：**

找出正确的序列并不容易，让我们看下面这个情况：

<img width=450 src="https://img.alicdn.com/imgextra/i2/O1CN01DXI8Cm1Uh1qjYGtEM_!!6000000002548-2-tps-1208-486.png">

贪心算法结束后，总长度是对的，但很明显顺序还是错的。为了方便计算，我们存储时转化为下标：

<img width=450 src="https://img.alicdn.com/imgextra/i3/O1CN01tflKTQ1soP0NpnIiu_!!6000000005813-2-tps-1216-716.png">

并且使用二维数组存储，这样被替换的数字可以被保留下来。当计算完毕后，我们从最后一位开始向前查找，**一旦发现一个值不是单调递减的，就向数组上方继续查找，直到首节点。**

因此上面的例子，最终顺序下标是 `[0, 1, 2, 3, 4, 5, 9]`，对应数字为 `[10, 20, 30, 40, 50, 60, 61]`，**而且这个数字是潜力最大的最长子序列。**

**Comment by LoonLi** [comment]
感谢迅速的回信！
对于二分确实没理解对，感谢说明。
对于找到正确的子序列顺序，感觉使用二维数组开销有点大，于是我去搜索了一下相关资料，在维基上找到了一个[只使用两个一维数组的方法](https://en.wikipedia.org/wiki/Longest_increasing_subsequence#:~:text=In%20computer%20science%2C%20the%20longest,not%20necessarily%20contiguous%2C%20or%20unique.)
对于新的例子大概是下面这个结果：

目标 X  [10,20,30,40,50,60,70,9,61,11,32]
贪心记录M [7,10,2,8,11,5,9] 对应数值[9,11,30,31,32,60,61]
坐标记录P [-1,0,1,2,3,4,5,-1,2,5,0,8] (对于P[i],记录X[i]在M中的前一个记录)
根据贪心记录的最后一个结果 61,坐标为9，从坐标记录P[9]开始往前读取，得到:
[10,20,30,40,50,60,61]

这个方法可能会更好。

**Comment by ascoders** [comment]
@LoonLi 这个方案很棒！压缩了无效信息简化空间复杂度。用法有点像并差集，学习了！
