### ISSUE TITLE
精读《新一代前端构建工具对比》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#316]
本周精读的文章是：[Comparing the New Generation of Build Tools](https://css-tricks.com/comparing-the-new-generation-of-build-tools/#feature-comparison)

将新兴构建工具：esbuild、Snowpack、Vite、wmr 做了一些功能对比，提前了解可以在选型时减少迷茫。

---

[精读《新一代前端构建工具对比》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/195.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%96%B0%E4%B8%80%E4%BB%A3%E5%89%8D%E7%AB%AF%E6%9E%84%E5%BB%BA%E5%B7%A5%E5%85%B7%E5%AF%B9%E6%AF%94%E3%80%8B.md)

**Comment by colgin** [comment]
> esbuild 有两大功能，分别是 bundler 与 minifier，其中 bundler 用于代码编译，类似 babel-loader、ts-loader；

这句话是不是有些有问题，esbuild官网上写的是 “An extremely fast JavaScript bundler”, 定了了esbuild是一个bundler，在[文档](https://esbuild.github.io/getting-started/#your-first-bundle) 可以看到效果。 babel-loader, ts-loader这些都不能叫bundler，准确来说应该叫 transpiler？或者说transformer吧？

**Comment by ascoders** [comment]
[esbuild github](https://github.com/evanw/esbuild) 写的是 “An extremely fast JavaScript bundler and minifier”，我认为叫把 loader 看作 bundler 过程的一部分还是合理的。transpiler 等称呼也可以，更清晰一些。
