### ISSUE TITLE
精读《前端职业规划 - 2021 年》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#317]
笔者对前端职业的认知每年都在刷新，因此有必要定期更新一下想法，形成文章记录下来。

---

[精读《前端职业规划 - 2021 年》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/196.%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%89%8D%E7%AB%AF%E8%81%8C%E4%B8%9A%E8%A7%84%E5%88%92%20-%202021%20%E5%B9%B4%E3%80%8B.md)

**Comment by s5s5** [comment]
也有很多业务逻辑主要在前端的项目啊，各种在线协作word excel figma ...

**Comment by usherwong** [comment]
收益了，感谢分享

**Comment by wjszxli** [comment]
知识分类和领域深耕深有同感，经济视角还想再补充一下，在经济学领域，有机会成本、沉没成本、边际效益等三个很重要的概念，其实这三个概念拿到我们技术领域来做是一个很有用的思考框架。

- 机会成本： 用机会成本去决策，如果这个事情、这个技术、这个业务我不做，不学，我会失去什么，对我的整个成长和职业生涯有什么影响？
- 沉没成本：用沉没成本去思考，如果目前这个工作对我成长是一个损耗，我是继续在这里和公司相互耗还是怎么办，如果接着耗，那我的沉没成本将会是越来越大。
- 边际效益对于工作时间长的同学比较有用，当工作年限上去了之后，就已经没有当初刚入行一样我学一个东西，对我技术上的带来很大的成长，而是学了或者了解了很多东西都没用，这个时候就需要深入思考，去寻找新的增长点，去学习能给你带来最大效益的东西，而不是浮于表面。

**楼主很优秀，是学习的榜样，期待我以后能够像你一样优秀**

**Comment by victorykong** [comment]
太赞了，工作两年的时间了，最近这段时间在痛苦中，很担心走错了方向。感谢分享！！！

**Comment by wangchong1994** [comment]
好文， 点赞

**Comment by codeghj** [comment]
thank you share

**Comment by ForeverJuvenile** [comment]
收益

**Comment by ForeverJuvenile** [comment]
受益

**Comment by HAjiMa666** [comment]
学习到了很多,自己也要努力,不要走错大方向
