### ISSUE TITLE
精读《export 默认/命名导出的区别》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#342]
本周精读的文章是：[export-default-thing-vs-thing-as-default](https://jakearchibald.com/2021/export-default-thing-vs-thing-as-default/)

加深你对 import、export 到底是引用还是瞬时值的理解，同时发现原来还有一些特殊语法糖存在作用域提升的效果。

---

[精读《export 默认/命名导出的区别》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/204.%E7%B2%BE%E8%AF%BB%E3%80%8A%E9%BB%98%E8%AE%A4%E3%80%81%E5%91%BD%E5%90%8D%E5%AF%BC%E5%87%BA%E7%9A%84%E5%8C%BA%E5%88%AB%E3%80%8B.md)

**Comment by atian25** [comment]
妈呀。。。 这么多坑。

我的结论是，我们需要 eslint-disable-esm-export-primitive

**Comment by Asarua** [comment]
这个厉害了

**Comment by CaiBirdZ** [comment]
受教了

**Comment by jay-lin1110** [comment]
`
/* export.js */
const a = {
  age: 1
}
let age = 111
setTimeout(() => {
  a.age = 233
  age = 666
})
// export default a/* 对象导出 */
export default {/* 字面量导出看似对象导出的简写，其实不同 */
  age
}

/* import.js */
import a from './chain.js'
console.log(a.age)
setTimeout(() => {
  console.log(a.age)
}, 1111)
`

**Comment by waitingsong** [comment]
尽量避免使用默认导出吧
