### ISSUE TITLE
能列出原文出处吗

### ISSUE THREAD

**Issue by conanskyforce** [ascoders/weekly#344]
每次看到title都是《精读XXX》，然后并没有找到《XXX》的原文，能麻烦分享的时候再加上原文链接吗

**Comment by ascoders** [comment]
所有有原文的都会贴地址，原创的不会贴。

近期大部分文章都是原创，所以才会感觉原文链接贴少了。

**Comment by ascoders** [comment]
主要原因还是前端高质量文章太少，欢迎推荐。
