### ISSUE TITLE
精读《Typescript infer 关键字》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#346]
本周精读的文章是 [conditional-infer](https://learntypescript.dev/09/l2-conditional-infer)。infer 这个关键字工作中比较少用到，但需要进行类型编程时却是必不可少的，本周我们一起学习一下吧。

---

[精读《Typescript infer 关键字》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/207.%E7%B2%BE%E8%AF%BB%E3%80%8ATypescript%20infer%20%E5%85%B3%E9%94%AE%E5%AD%97%E3%80%8B.md)

**Comment by feikerwu** [comment]
![image](https://user-images.githubusercontent.com/39146693/130388446-b41c6537-0695-49ec-b8fe-889b2c902837.png)
这里有个问题想讨论下，A 和 B 逆变为 A & B类型，根据集合论，也就是 A B交集，这种不是类型收敛吗，看到文章里把逆变看作类型发散，有点疑惑

**Comment by ascoders** [comment]
`&` 在 TS 里是并，`|` 是或的含义，不能套用集合含义。

另外类型收敛是指，TS 在类型推导时大部分情况是类型收敛的（收敛最类型安全），这也符合协变的规则（`|` 表示或，非 A 即 B 就是收敛）。

**Comment by baxtergu** [comment]
其实也可以简单理解为 `infer 的泛型` 在重复使用的情况下，具有类似泛型在条件类型上的 distributive 特性。

**Comment by 07akioni** [comment]
> ![image](https://user-images.githubusercontent.com/39146693/130388446-b41c6537-0695-49ec-b8fe-889b2c902837.png)
> 这里有个问题想讨论下，A 和 B 逆变为 A & B类型，根据集合论，也就是 A B交集，这种不是类型收敛吗，看到文章里把逆变看作类型发散，有点疑惑

这里确实容易引发歧义，因为没说清楚收敛的 source 和 target。

通俗说，协变就是满足约束多、或者说派生程度高的（人a）能赋值给约束少、或者说派生程度少的（动物b）值。

```
const a: 人 = ...
const b: 动物 = a
```

你也可以说 b 可以接受一个更收敛的值，也可以说 a 被赋给了更发散的变量。

**Comment by fuxiang123** [comment]
文中的例子
`type GetLabelTypeFromObject<T> = T extends ? { label: infer R } ? R : never`
第一个问号是不是多余的？

**Comment by 07akioni** [comment]
> 文中的例子
> `type GetLabelTypeFromObject<T> = T extends ? { label: infer R } ? R : never`
> 第一个问号是不是多余的？

没毛病

**Comment by soeasyjx** [comment]
type Bar<T> = T extends { a: (x: infer U) => void; b: (x: infer U) => void }
  ? U : never
type T21 = Bar<{ a: (x: string) => void; b: (x: number) => void }>;

请问你确定这个 T21 为 string & number 么?????????

**Comment by zhangyu1818** [comment]
楼上说的代码我放ts playground的结果是never，确实让人有一些疑惑
还有`type GetLabelTypeFromObject<T> = T extends ? { label: infer R } ? R : never`这个也会报错，第一个问号难道不是多余的吗？看见大佬们的发言让我对自己产生了疑惑，都不敢肯定自己了
