### ISSUE TITLE
精读《Typescript 4.4》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#348]
Typescript 4.4 版本有挺多有意思的升级，开始学习吧！文档地址：[https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/](announcing-typescript-4-4)

---

[精读《Typescript 4.4》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/208.%E7%B2%BE%E8%AF%BB%E3%80%8ATypescript%204.4%E3%80%8B.md)

**Comment by okbug** [comment]
```ts
let obj = {}
let arr = ['a', 'b', 'c', Symbol('a')]
arr.forEach(key => {
    obj[key as string] = 1
})
```

不知道这种情况，在新版本中有没有什么解决办法？
在之前的版本中，报错key只能是string，并且在这其中，symbol是如何转的呢？

**Comment by baxtergu** [comment]
> ```ts
> let obj = {}
> let arr = ['a', 'b', 'c', Symbol('a')]
> arr.forEach(key => {
>     obj[key as string] = 1
> })
> ```
> 
> 不知道这种情况，在新版本中有没有什么解决办法？
> 在之前的版本中，报错key只能是string，并且在这其中，symbol as string后是如何转的呢？如果是toString的话岂不是有可能有两个不一样的会变成一样的？

可以通过手工指定 obj 中 key 的具体可能类型来解决，而不是用默认的隐式 any 类型

```typescript
type stringOrSymbolKeyedObject = {
  [key: string]: number,
  [sym: symbol]: number
}

let obj: stringOrSymbolKeyedObject = {}

let arr = ['a', 'b', 'c', Symbol('a')]
arr.forEach(key => {
  obj[key] = 1
})
```

或者也可以从具体数组值中获取类型集合

```typescript
let arr = ['a', 'b', 'c', Symbol('a')]

let obj: { [key: typeof arr[number]]: number } = {}

arr.forEach(key => {
  obj[key] = 1
})
```
