### ISSUE TITLE
how to contribute to 前端精读周刊

### ISSUE THREAD

**Issue by liuyingbin1922** [ascoders/weekly#352]
如何贡献前端精读周刊？

**Comment by ascoders** [comment]
你好，前端精读周刊贡献方式是：**直接提交文章 MR，文章放到对应文件夹下，且序号自增即可**。有几个注意点：

1. 在文章正文里写上署名。
2. 文章发布日期为 MR 合并后第二天上午。
3. 会同时发送到 [知乎](https://zhuanlan.zhihu.com/FrontendPerusal)、[掘金](https://juejin.cn/column/6960554858210394148)、[思否](https://segmentfault.com/blog/jingdu)、微信公众号。

**Comment by liuyingbin1922** [comment]
receive
