### ISSUE TITLE
刚读完第二篇文章，模态框最佳实践。真的最佳吗？

### ISSUE THREAD

**Issue by zhea55** [ascoders/weekly#357]
> 对于 table 操作列中触发的模态框，所有行都对应一个模态框，通过父级中一个状态变量来控制展示的内容

这个是不是太小白了。

table里面循环的行数据，明显复用一个模态框就够了。模态框里面只是数据不同，没有必要每行都渲染一个。

**Comment by ascoders** [comment]
这个简单道理需要不断重复，因为写这种代码的人还不少，至少我一直看到类似的代码。

不过 table 里重复渲染 Modal 是比较少见的，比较多见的是非 table 场景，比如渲染一个 list 时，图方便就把 Modal 写在每个 Item 里了，实际上每个 Item 的 Modal 逻辑也都是一样的。

我希望永远没有这种代码，但这种代码永远出现在我的周围。

**Comment by zhea55** [comment]
@ascoders 

没有办法的，大环境我们改变不了，做好自己的。

就像这篇文章一样，大概率是这个仓库的作者复制过来的，或者翻译过来的。

自己也没有研究过，反正就发出来。

到处炫耀，我的仓库多少星拉，我要涨工资。


实际分享的东西，他自己估计都没有看过。


我们认真，我们就输了。这个环境，浮躁的很。

**Comment by ascoders** [comment]
哈哈，我就是这个仓库作者。这句话写的是有歧义： “所有行都对应一个 Modal” ，其实想表达的意思是，对应唯一一个 Modal，但这句话容易被理解为每行一个 Modal。

有歧义的地方 @xiangwan 同学已经提 MR 改过来了，感谢他！

还有一个歧义要说明，这篇文章并不想哗众取宠取 “最佳实践”  的名字，而是精读的原文 [Best Practices for Modals / Overlays / Dialog Windows](https://uxplanet.org/best-practices-for-modals-overlays-dialog-windows-c00c66cddd8c) 中文含义就是最佳实践，这里只是说明精读的文章标题，没有别的意思。

最后借机会说明一下，本人没有靠精读涨过工资，每篇文章都是仔细阅读后写的，还有大量是完全原创文章。引用第一篇精读的第一句话，说明我做精读的初衷：

> 这次是前端精读期刊与大家第一次正式碰面，我们每周会精读并分析若干篇精品好文，试图讨论出结论性观点。没错，我们试图通过观点的碰撞，争做无主观精品好文的意见领袖。
