### ISSUE TITLE
精读《Rust 是 JS 基建的未来》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#371]
[Rust Is The Future of JavaScript Infrastructure](https://leerob.io/blog/rust) 这篇文章标题看着有点夸张，但事实可能真的如此。Rust 作为一门较新的语言（2006 年开始开发，2010 年发布 0.1.0 版本），最近正在被用来改造前端基建工具的生态，因为它的速度实在比 Node 快太多了，随随便便就是 10x 的性能提升，让研发团队几乎没有理由拒绝它。

---

[精读《Rust 是 JS 基建的未来》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/218.%E7%B2%BE%E8%AF%BB%E3%80%8ARust%20%E6%98%AF%20JS%20%E5%9F%BA%E5%BB%BA%E7%9A%84%E6%9C%AA%E6%9D%A5%E3%80%8B.md)

**Comment by kibuniverse** [comment]
还有 neon, https://github.com/neon-bindings/neon, 可以将 rust 编译为二进制文件并且可以在 node 中直接 require 进行引用

**Comment by lmxyjy** [comment]
对于前端来说，无疑增加了学习成本。不知道什么时候能取代webpack的地位，1年？2年或者更久。

**Comment by frmachao** [comment]
为什么社区大多选择了 Rust ，而不是 golang？

**Comment by ascoders** [comment]
> 为什么社区大多选择了 Rust ，而不是 golang？

https://zhuanlan.zhihu.com/p/436090437 这篇推荐回复有解答，一方面确实是特性导致的，当然也有社区 swc 的促进。
