### ISSUE TITLE
精读《深入了解现代浏览器一》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#374]
[Inside look at modern web browser](https://developers.google.com/web/updates/2018/09/inside-browser-part1) 是介绍浏览器实现原理的系列文章，共 4 篇，本次精读介绍第一篇。

虽然本文写于 2018 年，但如今依然值得学习，因为浏览器实现非常复杂，从细节开始学习很容易迷失方向，缺乏整体感，而这篇文章从宏观层面开始介绍，几乎没有涉及代码实现，全都是思路性的描述，非常适合培养对浏览器整体框架性思维。

---

[精读《深入了解现代浏览器一》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/219.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%80%E3%80%8B.md)

**Comment by leohxj** [comment]
想知道为什么 GPU 进程不是和 renderer 进程一一对应, 这样绘制不是更高效吗?
另外还有哪些类型进程是可能多个的?

**Comment by ascoders** [comment]
@leohxj 1. 一一对应是什么意思？ 2. 渲染、插件进程可能是多个，部分是出于安全隔离的考虑。

**Comment by leohxj** [comment]
> @leohxj 1. 一一对应是什么意思？ 2. 渲染、插件进程可能是多个，部分是出于安全隔离的考虑。

想说为什么只有一个 GPU 进程, 而不是想 renderer 那样沙盒机制

**Comment by ascoders** [comment]
@leohxj 这部分我了解不深入，列几个可能的原因：
1. 进程不是越多越好，浏览器在遇到性能强劲的电脑才会开启多进程模式，但大部分情况一个进程就够了，仅需要安全隔离的情况才被迫启用多进程，因为进程间资源隔离是操作系统保障的，杜绝了安全问题。
2. 与渲染进程可执行任意 JS 脚本不同，GPU 进程运行的逻辑更可控，不需要做资源间的安全隔离。
3. GPU 本身是一种系统资源，开了多个进程可能也不会增强系统 GPU 的能力；反观渲染进程，本身属于自定义程序脚本的一部分，开多个进程就可以并发，在合理数量内，多个进程并行可能比串行效率高。

**Comment by a243065157** [comment]
收到
