### ISSUE TITLE
精读《深入了解现代浏览器二》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#375]
本次解读 [深入了解现代浏览器 第二篇](https://developers.google.com/web/updates/2018/09/inside-browser-part2)

---

[精读《深入了解现代浏览器二》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/220.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E4%BA%8C%E3%80%8B.md)

**Comment by txs1992** [comment]
browser process 包含 UI thread、network thread 和 storage thread，这句话是否标准，第一篇中不是说浏览器中模块可能会是一个独立的进程吗？
