### ISSUE TITLE
请问一下作者的文章是用什么工具写的？

### ISSUE THREAD

**Issue by SimonTart** [ascoders/weekly#377]
请问一下作者的文章是用什么工具写的，我看图片都不在项目中。我也想像作者这样写文章。

**Comment by ascoders** [comment]
我直接用 vscode 写的，有一些 markdown 插件可以配合。图片是提前上传好的，我一般用 https://imgtu.com/ 这个平台传图。

**Comment by SimonTart** [comment]
好的，谢谢
