### ISSUE TITLE
精读《深入了解现代浏览器三》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#379]
本次解读 [深入了解现代浏览器 第三篇](https://developers.google.com/web/updates/2018/09/inside-browser-part3)

---

[精读《深入了解现代浏览器三》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/221.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%89%E3%80%8B.md)

**Comment by Ray-56** [comment]
勘误

https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/221.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%89%E3%80%8B.md#%E8%A7%A3%E6%9E%90%E9%98%B6%E6%AE%B5

> 解析阶段
> 首先 renderer process 主线程会解析 HTML 文本为 DOM（Document Object Model），只译为中文就是文档对象模型，所以首先要把文本结构化才能继续处理。不仅是浏览器，代码的解析也得首先经历 Parse 阶段。

这里的`只译`是直译的意思么

**Comment by ascoders** [comment]
> 这里的`只译`是直译的意思么

是的，已修复，🙏。
