### ISSUE TITLE
精读《深入了解现代浏览器四》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#381]
解读深入了解现代浏览器系列的最后一篇：[Inside look at modern web browser (part 4) ](https://developers.google.com/web/updates/2018/09/inside-browser-part4)

---

[精读《深入了解现代浏览器四》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/222.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9B%9B%E3%80%8B.md)

**Comment by Bluestar123** [comment]
如果与浏览器主线程解耦的化效率会非常高， 应该是 ‘话’ 这个字吧

**Comment by Bluestar123** [comment]
请问下，breakchange 应该怎么理解

**Comment by ascoders** [comment]
> 请问下，breakchange 应该怎么理解

React 如果什么都不做，就从 `passive` 变成 `non-passive` 了，这种行为变化是 break change 的一种表现。
