### ISSUE TITLE
精读《Records & Tuples 提案》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#384]
也许你觉得 js 通过 immutablejs、immer 等库已经很好的支持了 immutable，但看下面这个问题：

> 你在控制台看到应用数据从 `{ a: 1 }` 变成了 `{ a: 1}`，能解读出什么？这两个对象是否相同完全取决于引用是否相同，但引用是否相同我们根本看不出来，这取决于如何实现的。也就是说，**`{ a: 1} === { a: 1 }` 或者 `{ a: 1} !== { a: 1 }` 都有可能。**

对，就是这个问题，在现在 js 是无解的。你可以保证 “我实现严格遵循 immutable”，但我反问 “鬼知道你的实现有没有问题？？”，稍微不小心写个默认值就会导致一个新引用 `obj ?? []`，谁敢保证不犯错呢？

https://github.com/tc39/proposal-record-tuple 解决的就是这个问题，它让肉眼看上去的相等绝对相等： `#{ a: 1 } === #{ a: 1}`，原因是通过 `#` 符号填补了之前隐晦的引用关系。

---

[精读《Records & Tuples 提案》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/223.%E7%B2%BE%E8%AF%BB%E3%80%8ARecords%20%26%20Tuples%20%E6%8F%90%E6%A1%88%E3%80%8B.md)

**Comment by LastKnightCoder** [comment]
发现文中有一个矛盾的地方

<img src="https://user-images.githubusercontent.com/29890094/147443652-242ea639-5e96-45d6-a8ed-1328507789cc.png" style="zoom: 50%;">

所以 `Object.keys(#{a: 1, b:2}) === #["a", "b"]` 吗

**Comment by ascoders** [comment]
> 发现文中有一个矛盾的地方
> 
> ![](https://user-images.githubusercontent.com/29890094/147443652-242ea639-5e96-45d6-a8ed-1328507789cc.png)
> 
> 所以 `Object.keys(#{a: 1, b:2}) === #["a", "b"]` 吗

看上去是提案写错了，第二段代码是错误的，因为 `Object.keys(#{ a: 1, b: 2 })` 结果是一个普通数组。
