### ISSUE TITLE
精读《Excel JS API》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#387]
Excel 出 js API 了，赋予了开发者更强大能力，我们一起了解下，官方 API 文档：[Excel JavaScript API overview](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview)

---

[精读《Excel JS API》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/225.%E7%B2%BE%E8%AF%BB%E3%80%8AExcel%20JS%20API%E3%80%8B.md)

**Comment by waitingsong** [comment]
JS 无处不在。难道应了那句话……
