### ISSUE TITLE
指出周刊中的一处错误，css禁用滚动属性

### ISSUE THREAD

**Issue by Caozefu** [ascoders/weekly#389]
https://github.com/ascoders/weekly/blob/d4d87b029f000f24c0834ddcbda6e224083e07d3/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/222.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3%E7%8E%B0%E4%BB%A3%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9B%9B%E3%80%8B.md?plain=1#L72

此处应该是touch-action: none禁用滚动，pan-x代表可以x方向touch操作

**Comment by ascoders** [comment]
已修复。
