### ISSUE TITLE
精读《2021 前端新秀回顾》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#390]
已经 2022 年了，[2021 JavaScript Rising Stars](https://risingstars.js.org/2021/en) 列出了 2021 年内前端各领域 Star 增势排行榜，这些势头在 2022 年大概率会保持下来，所以抓住这些趋势，如果还不熟悉就趁机了解一下。

---

[精读《2021 前端新秀回顾》 ](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/226.%E7%B2%BE%E8%AF%BB%E3%80%8A2021%20%E5%89%8D%E7%AB%AF%E6%96%B0%E7%A7%80%E5%9B%9E%E9%A1%BE%E3%80%8B.md)

**Comment by wednesday** [comment]
> 第二名 [nest](https://github.com/nestjs/nest) 和 next.js 很像，据我当时的了解，是因为 next.js 起步较慢，源码还不支持 ts，所以就有了这个更时髦的新框架。但实际上 next.js 早就全部改为 ts 了，而且正如整体榜单所说，现在已经开始引领潮流了，所以不怪 nest 定位重合，只能怪 next.js 后续发力太猛了。nest 的唯一特点就是没有绑定 UI 库。

nest 和 next完全不是一个定位的东西

**Comment by a243065157** [comment]
收到
