### ISSUE TITLE
精读《zustand 源码》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#392]
[zustand](https://github.com/pmndrs/zustand) 是一个基于 Redux + Context 思想（并不依赖 redux）的数据流管理工具，并暴露 Hooks API，非常时髦，值得学习一下 API 与实现原理。

---

[精读《zustand 源码》](https://github.com/ascoders/weekly/blob/master/%E6%BA%90%E7%A0%81%E8%A7%A3%E8%AF%BB/227.%20%E7%B2%BE%E8%AF%BB%E3%80%8Azustand%20%E6%BA%90%E7%A0%81%E3%80%8B.md)

**Comment by tangdw** [comment]
![image](https://user-images.githubusercontent.com/17575065/150761828-1f809145-2959-4655-ace8-ca396ea5e85f.png)
"compare 函数" 对比的是 useCallback 返回值（函数）的执行结果，对比是否为 true 不一定

**Comment by ascoders** [comment]
> ![image](https://user-images.githubusercontent.com/17575065/150761828-1f809145-2959-4655-ace8-ca396ea5e85f.png) "compare 函数" 对比的是 useCallback 返回值（函数）的执行结果，对比是否为 true 不一定

嗯，这样写更准确，useCallback 返回值就是函数。

**Comment by dontry** [comment]
最近看了zustand，现在它用了“React.useSyncExternalStore()"这个hook。连context都省掉了
