### ISSUE TITLE
精读《对 Markdown 的思考》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#397]
[Thoughts On Markdown](https://www.smashingmagazine.com/2022/02/thoughts-on-markdown/) 这篇文章提出了 Markdown 的一些反思。作者本身有大量 Markdown 使用经验，分析的比较有道理，我们一起读一读，作为一些技术选型时的背景知识吧。

---

[精读《对 Markdown 的思考》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/230.%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%AF%B9%20Markdown%20%E7%9A%84%E6%80%9D%E8%80%83%E3%80%8B.md)

**Comment by cdswyda** [comment]
mardown 写和存储确实是方便，但稍微复杂点的内容确实难处理。 交互问题则更难。
像语雀、notion 这种现代的区块编辑器上，目前来看体验是当下比较完美的，但是这种内容的存储上和如何设计的呢？

**Comment by 0x219** [comment]
> markdown 写和存储确实是方便，但稍微复杂点的内容确实难处理。 交互问题则更难。 像语雀、notion 这种现代的区块编辑器上，目前来看体验是当下比较完美的，但是这种内容的存储上和如何设计的呢？

block协议

**Comment by caozhong1996** [comment]
我的理解是编辑器需要支持md语法，储存也可以储存为md格式。至于富交互，其实就是个渲染的问题。

**Comment by ascoders** [comment]
编辑器可以支持 md 语法，但存储格式是 json 而不是 md。内容输出可以转化为 md 格式，但特殊区块或 md 不支持描述的功能就无法转换，此时可以选择抛弃或给出转换提示。

**Comment by Bluestar123** [comment]
<tabke></table>。文章这里的标签写错了

**Comment by ascoders** [comment]
> 。文章这里的标签写错了

哪里。。

**Comment by atian25** [comment]
这也是我这几年从 MD 转为 语雀 的原因之一，我们需要的实际上只是类 MD 的输入体验，如快捷键啥的。

**Comment by Bluestar123** [comment]
Markdown 语法拓展小节  table 标签哪里，贴标签没显示。。。

**Comment by Bluestar123** [comment]
> > 。文章这里的标签写错了
> 
> 哪里。。

Markdown 语法拓展小节 table 标签哪里，贴标签没显示。。。

**Comment by ascoders** [comment]
> Markdown 语法拓展小节 table 标签哪里，贴标签没显示。。。

我看到了一处 typo 已修复，如果还有问题，可以辛苦提个 mr。

**Comment by Bluestar123** [comment]
现在考虑mdx方式写组件库，问下大佬，语雀是不是也是自己实现的一套规范，也没有通用的方案？

**Comment by Bluestar123** [comment]
> > Markdown 语法拓展小节 table 标签哪里，贴标签没显示。。。
> 
> 我看到了一处 typo 已修复，如果还有问题，可以辛苦提个 mr。

好的，积极参与

**Comment by ascoders** [comment]
@Bluestar123 肯定有自己的规范，但细节我不了解。这种规范不像 markdown 或 jsonSchema 那么成熟，据我了解还没有标准组织去标准化它，如果其他同学见过欢迎补充。

**Comment by maqi1520** [comment]
看了这篇文章后我写了一个微信编辑器

【开源自荐】基于MDX 的微信排版编辑器，可自定义组件、样式、可导出 markdown 和 PDF
在线地址：https://editor.runjs.cool/
代码仓库：https://github.com/maqi1520/mdx-editor
