### ISSUE TITLE
精读《SQL 窗口函数》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#405]
窗口函数是数据分析领域的重要处理函数，比如累计求和或者累计平均等常见数据分析功能都需要借助此能力实现。

---

[SQL 窗口函数](https://github.com/ascoders/weekly/blob/master/SQL/235.SQL%20%E7%AA%97%E5%8F%A3%E5%87%BD%E6%95%B0.md)

**Comment by jasonslyvia** [comment]
weekly 开始跨学科精读了吗😂

**Comment by kang8** [comment]
想知道 SQL 是专指某一个 SQL，比如 MySQL。还是泛指所有接口。

**Comment by ascoders** [comment]
> 想知道 SQL 是专指某一个 SQL，比如 MySQL。还是泛指所有接口。

泛指所有，因为现在学某一种 SQL 引擎没意义。现在大数据处理平台一般会在语法层面抹平差异，或数据抽取到某种专用 DB。
