### ISSUE TITLE
精读《不再需要 JS 做的 5 件事》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#413]
这次选择 [5 things you don't need Javascript for](https://lexoral.com/blog/you-dont-need-js/) 的原因是，我们已经在 JS 专精的路上跑了太久，是时候回头看看 CSS 与 SVG 取得的进展。这篇文章以 5 个原本只能用 JS 实现，而现在可以用 CSS 实现的场景提醒了我们关注 JS 以外的生态，并且这些例子都非常实用，让人一下就可以记住。

---

[精读《不再需要 JS 做的 5 件事》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/238.%E7%B2%BE%E8%AF%BB%E3%80%8A%E4%B8%8D%E5%86%8D%E9%9C%80%E8%A6%81%20JS%20%E5%81%9A%E7%9A%84%205%20%E4%BB%B6%E4%BA%8B%E3%80%8B.md)

**Comment by waitingsong** [comment]
英文原文的逻辑结构是
标题：5 things you don't need Javascript for
小节： Animating SVGs

小节名是名词，对应的是标题中 `things` 名词

译文逻辑结构是
标题：精读《不再需要 JS 做的 5 件事》
小节：**使用** css 控制 svg 动画

小节名是动词，对应不上标题内的名词 `事` 。容易让读者混淆

**Comment by ascoders** [comment]
确实我漏看了，感谢指正，文章名改的话链接就失效了，所以只好不改啦。
