### ISSUE TITLE
精读《JS 数组的内部实现》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#414]
本周卷一卷 v8 原理之，JS 数组的内部实现，精读文章为：[How JavaScript Array Works Internally?](https://blog.gauravthakur.in/how-javascript-array-works-internally)

---

[精读《JS 数组的内部实现》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/239.%E7%B2%BE%E8%AF%BB%E3%80%8AJS%20%E6%95%B0%E7%BB%84%E7%9A%84%E5%86%85%E9%83%A8%E5%AE%9E%E7%8E%B0%E3%80%8B.md)

**Comment by nightire** [comment]
> 这张图的备注是不是有点问题？

你是对的，`new Array()` 才是 `HOLEY_SMI_ELEMENTS`

**Comment by nightire** [comment]
建议直接把 Holey 解释成“稀疏数组”就好了，原文其实也是这么解释的，比“孔洞”听起来要舒服多了：

> Holey elements mean that there are gaps in the array. It represents the **sparse array**.

**Comment by lozyue** [comment]
How about the implementation of Array<Object> in javascript V8 or SpiderMonkey? I was wondering whether it is random-accessible fast-array if I initialize an array with `JSON.parse` which returns an array containing thousands of Plain Objects. May it correspond to the PACKED_ELEMENTS within this article? Sorry for commenting on closed issue.
---
请问对象数组在javascript V8或SpiderMonkey中是如何实现的? 如果我用`JSON.parse`的方式初始化一个包含数千个纯对象的数组，我想知道它是否是具有可随机访问特性的快数组。它与本文中的PACKED_ELEMENTS 相对应吗?
