### ISSUE TITLE
精读《type challenges - easy》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#422]
读一读[类型挑战](https://github.com/type-challenges/type-challenges) - easy 难度的题目，总结一下用到了哪些特性与思维方式。

---

[精读《type challenges - easy》](https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/243.%E7%B2%BE%E8%AF%BB%E3%80%8Atype%20challenges%20-%20easy%E3%80%8B.md)

**Comment by huyansheng3** [comment]
![image](https://user-images.githubusercontent.com/11534583/173272372-348ce760-9cec-4585-afbe-4b6c6fef8d39.png)

Last 第二个参数设置为默认值似乎也是合法的？

**Comment by ascoders** [comment]
对，因为默认值写的是 `any[]` 而不是 `[]`，当然此时 `Others` 类型就定死了是 `any[]` 而不是 `['1', '2']` 了，只解决当前问题，但 `Others` 类型不清晰，还是有潜在问题的。

**Comment by likoshow** [comment]
元组长度这边，应该还要考虑 readonly。

**Comment by waitingsong** [comment]
> 这个Equal 好像不行，写什么上去都是ture ![image](https://user-images.githubusercontent.com/61933017/180012083-4cb60196-9d32-4d6a-944d-4d8fe99e7dff.png)

[试试这个](https://github.com/waitingsong/shared/blob/726a2519e9853e0dcd5fbf62249c573fd3790229/packages/types/src/lib/common.ts#L47)

**Comment by MyKyle19** [comment]
[Pick](https://github.com/type-challenges/type-challenges/blob/main/questions/00004-easy-pick/README.md)
Pick的答案二应该是
`type MyPick<T, K extends keyof T> = {
  [P in K]: T[P]
}`

**Comment by wxh-cyber** [comment]
Await的答案，作者给的有错误。
```ts
type MyAwaited<T extends Promise<unknown>> = T extends Promise<infer P> ? (P extends Promise<unknown> ? MyAwaited<P> : P) : never;

//测试案例
type T = { then: (onfulfilled: (arg: number) => any) => any }

```
写成上面这种形式，最后一个测试案例无法通过。这是因为在TS中，通过Promise<T>表示一个泛型类型，它提供了完整的异步操作处理机制，包括错误处理、链式调用和async/await支持。而PromiseLike仅要求对象具有then方法，功能可能不完整。因此PromiseLike主要用于类型兼容性和泛型编程中。在最后一个测试案例中，由于最后一个对象T是一个固定的函数类型，不带有Promise类型，因此应该采用PromiseLike。在后面的泛型中，由于unknown类型会进行Promise的断言检查，而最后一个测试案例不满足该要求，故泛型应该为any而不是unknown。
```ts
type MyAwaited<T extends PromiseLike<any>> = T extends PromiseLike<infer P> ? (P extends PromiseLike<any> ? MyAwaited<P> : P) : never;
```

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。

**Comment by a243065157** [comment]
收到

**Comment by wxh-cyber** [comment]
**8.readonly2存在的问题**
```ts
//存在小问题的答案
type MyReadonly2<T, K extends keyof T> = Readonly<Pick<T, K>> & Omit<T, K>;
```
如果对于泛型K没有指定默认值，则泛型K为必填选项，无法跑通第一个案例，即仅存在单个T，而不存在K的情况。
