### ISSUE TITLE
精读《Promise.all, Replace, Type Lookup...》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#425]
精读 [type-challenges](https://github.com/type-challenges/type-challenges) Medium 9~16 题。

---

[精读《Promise.all, Replace, Type Lookup...》](https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/245.%E7%B2%BE%E8%AF%BB%E3%80%8APromise.all%2C%20Replace%2C%20Type%20Lookup...%E3%80%8B.md)

**Comment by waitingsong** [comment]
> 不知道是 bug 还是 feature，TS 的 { [K in keyof T]: T[K] } 能同时兼容元组、数组与对象类型。

`keyof T` 的结果是 string | number | symbol，T[number] 自然就兼容数据了～
