### ISSUE TITLE
精读《MinusOne, PickByType, StartsWith...》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#430]
精读 [type-challenges](https://github.com/type-challenges/type-challenges) Medium 33~40 题。

---

[精读《MinusOne, PickByType, StartsWith...》](https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/248.%E7%B2%BE%E8%AF%BB%E3%80%8AMinusOne%2C%20PickByType%2C%20StartsWith...%E3%80%8B.md)

**Comment by waitingsong** [comment]
这儿顺序反了： https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/248.%E7%B2%BE%E8%AF%BB%E3%80%8AMinusOne%2C%20PickByType%2C%20StartsWith...%E3%80%8B.md#mutable

```
把对象从不可写变成可写：

type Readonly<T> = {
  readonly [K in keyof T]: T[K]
}

从可写改成不可写也简单，主要看你是否记住了这个语法：-readonly：

// 本题答案
type Mutable<T extends object> = {
  -readonly [K in keyof T]: T[K]
}
```

**Comment by ascoders** [comment]
感谢指正，已更正
