### ISSUE TITLE
精读《ObjectEntries, Shift, Reverse...》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#431]
精读 [type-challenges](https://github.com/type-challenges/type-challenges) Medium 41~48 题。

---

[精读《ObjectEntries, Shift, Reverse...》](https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/249.%E7%B2%BE%E8%AF%BB%E3%80%8AObjectEntries%2C%20Shift%2C%20Reverse...%E3%80%8B.md)

**Comment by waitingsong** [comment]
[Shift](https://github.com/ascoders/weekly/blob/master/TS%20%E7%B1%BB%E5%9E%8B%E4%BD%93%E6%93%8D/249.%E7%B2%BE%E8%AF%BB%E3%80%8AObjectEntries%2C%20Shift%2C%20Reverse...%E3%80%8B.md#shift) 解法不满足空数组（元组）场景

```ts
type Result = Shift<[3, 2, 1]> // [2, 1]   // 满足
type Result = Shift<[]> // never ， 不满足 js 的处理结果 []
```
[改进解法](https://github.com/type-challenges/type-challenges/issues/13209)

**Comment by Henry-Diasa** [comment]
首先回忆一下二叉树中序遍历 JS 版的实现：

`
function inorderTraversal(tree) {
  if (!tree) return []
  return [
    ...inorderTraversal(tree.left),
    res.push(val),
    ...inorderTraversal(tree.right)
  ]
}
`
感觉这个位置JS实现的中序遍历不严谨，当然大概意思是都可以看懂的。
