### ISSUE TITLE
精读《SolidJS》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#438]
本周精读的文章是 [SolidJS](https://www.loginradius.com/blog/engineering/guest-post/introduction-to-solidjs/)，了解下 SolidJS 设计理念。

---

[精读《SolidJS》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/255.%E7%B2%BE%E8%AF%BB%E3%80%8ASolidJS%E3%80%8B.md)

**Comment by ununian** [comment]
响应式那块看起来有点像 vue，所以依赖收集才是版本答案吗

**Comment by townechow** [comment]
看到最后突然笑抽了：「我这个太阳能手电筒才是真正的伟大发明！」「那没有太阳的时候怎么办？」「拿另一个手电筒照着它就能亮了...」🤣🤣
solidjs 或许是真正的数据响应式，但是连最基本的 prop 解构都不支持，在工程项目中根本没法用的说...
不过，估计在 react  下一次的版本大升级就会向 solidjs **致敬** ༼ つ ◕_◕ ༽つ

**Comment by HiWayne** [comment]
文章对solid介绍写的不错，但个人对文中一些react的理解不是很认可，所以补充一些看法。

1. `而 React 的所有生命周期和状态监听函数都是 useEffect，虽然看上去更简洁，但即便是精通 React Hooks 的老手也不容易判断哪些是监听，哪些是生命周期』`

开发者对useEffect并不需要『判断哪些是监听，哪些是生命周期』。用useEffect来监听变化本身就不一定合适的。只需要记住它只有一个功能，就是放副作用。react官方已经说过可以用v15的生命周期帮助理解useEffect，但不要把它们划等号。本质上它是FP里的monad。

2. `React Hooks 使用 deps 收集依赖，在下次执行渲染函数体时，因为没有任何办法标识 “deps 是为哪个 Hook 申明的”，只能依靠顺序作为标识依据，所以需要稳定的顺序，因此不能出现条件分支在前面`

这里的『收集依赖』可能是为了让大家更好理解，但也容易让人误以为react里有『收集依赖』这种机制。关于hooks的流程，详细的说，假设当事组件叫A，A中使用了3个`useState`。使用`useState`时，react会在当前fiber节点中创建hook对象。A中使用了多个hook，于是后续的hooks都会跟在上一个hook对象的next属性上形成一个链表。这是因为`hooks`不使用任何标识符记录自己，于是只能隐式利用顺序来寻找。用`setState`更新时，当事组件A会重新render，执行到3个hooks时，会依次沿着链表寻找。所以必须严格依赖顺序。

**Comment by laoergege** [comment]
如果 vue 也改成点对点的更新，那么 vue 性能是不是也跟得上 SolidJS？不过之前看过，好像 vue1 就是点对点更新，但后来就改成 vdom diff 机制。。。

**Comment by inceptiongt** [comment]
props是可以解构的：`const App = ({ userName }) => <div>{userName}</div>;`
只要userName是个完整的signal就行，splitProps也是以signal为单位来分割。

准确说是signal是不能解构的，因为signal是浅层响应的。createStore是深层响应的，类似于Vue的reactive，而且可以解构到倒数第二层

**Comment by inceptiongt** [comment]
> 如果 vue 也改成点对点的更新，那么 vue 性能是不是也跟得上 SolidJS？不过之前看过，好像 vue1 就是点对点更新，但后来就改成 vdom diff 机制。。。

为啥呢

**Comment by Genuifx** [comment]
核心的响应式实现是发布订阅模式依赖收集，这点和vue2和实现是高度相似的，store 部分通过 Proxy 实现和vue3类似。
