### ISSUE TITLE
设计模式-Adapter（适配器模式）

### ISSUE THREAD

**Issue by benyoutop** [ascoders/weekly#439]
![image](https://user-images.githubusercontent.com/96740028/188040924-f039d1ec-8258-41f2-8e88-de295d9ca8e7.png)
大佬，这儿注释说是继承Adaptee了，这儿是注释有问题，还是我遗漏了一些知识点。
文章链接：https://github.com/ascoders/weekly/blob/master/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/172.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Adapter%20%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F%E3%80%8B.md

**Comment by ascoders** [comment]
这是以组合的方式实现继承

**Comment by benyoutop** [comment]
谢谢大佬
