### ISSUE TITLE
精读《依赖注入简介》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#440]
精读文章：[Dependency Injection in JS/TS – Part 1](https://blog.codeminer42.com/dependency-injection-in-js-ts-part-1/)
了解一下依赖注入思维和实现。

---

[精读《依赖注入简介》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/256.%E7%B2%BE%E8%AF%BB%E3%80%8A%E4%BE%9D%E8%B5%96%E6%B3%A8%E5%85%A5%E7%AE%80%E4%BB%8B%E3%80%8B.md)

**Comment by HiWayne** [comment]
能介绍一下为什么spring解决循环依赖设计成3层缓存吗？node里的request.js解决模块的循环依赖只用了1层缓存。

**Comment by ascoders** [comment]
我还没有水平可以几句话讲清楚，应该和 AOP 的代理对象创建流程有关，有经验的同学可以评论一下。

**Comment by NameWjp** [comment]
保证依赖顺序正确那里讲的很棒，感谢分享🙏

**Comment by zeyongTsai** [comment]
```js
export type RandomGenerator = () => number;

export const randomNumberImplementation =
  ({ randomGenerator }: Deps) =>
  (max: number): number => {
    return Math.floor(randomGenerator() * (max + 1));
  };

export const randomNumber = (max: number) =>
  randomNumberImplementation(Math.random, max);
```
这段代码不对吧，上面不是一个 HOC 吗？

**Comment by a243065157** [comment]
收到

**Comment by xjq7** [comment]
@HiWayne 你是指 commonjs 的循环依赖吗
