### ISSUE TITLE
精读《State of CSS 2022》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#442]
精读文章：[State of CSS 2022](https://web.dev/state-of-css-2022/#color-spaces) 
Google IO 2022 介绍了一些新的 CSS feature，该文章是演讲的文字稿，一起更新一下 CSS 知识储备吧。

---

[精读《State of CSS 2022》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/257.%E7%B2%BE%E8%AF%BB%E3%80%8AState%20of%20CSS%202022%E3%80%8B.md)

**Comment by wmasfoe** [comment]
大佬 `@container` 那里没设置 `container-type`
按照示例代码我发现只设置 `container-name` 不生效。
献上代码：
[codesandbox](https://codesandbox.io/s/practical-jasper-tfi9v1?file=/index.html)
参考了下 [这个](https://www.zhangxinxu.com/wordpress/2022/09/css-container-rule/#:~:text=%E5%9B%9B%E3%80%81-,%E8%AF%B4%E8%AF%B4container%E5%B1%9E%E6%80%A7,-container%E5%B1%9E%E6%80%A7%E6%98%AF)
