### ISSUE TITLE
精读《Headless 组件用法与原理》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#444]
Headless 组件即无 UI 组件，框架仅提供逻辑，UI 交给业务实现。这样带来的好处是业务有极大的 UI 自定义空间，而对框架来说，只考虑逻辑可以让自己更轻松的覆盖更多场景，满足更多开发者不同的诉求。

我们以 [headlessui-tabs](https://headlessui.com/react/tabs) 为例看看它的用法，并读一读 [源码](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/tabs/tabs.tsx)。

---

[精读《Headless 组件用法与原理》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/259.%E7%B2%BE%E8%AF%BB%E3%80%8AHeadless%20%E7%BB%84%E4%BB%B6%E7%94%A8%E6%B3%95%E4%B8%8E%E5%8E%9F%E7%90%86%E3%80%8B.md)

**Comment by Yunkou** [comment]
Headless 最近接触了一个框架，在处理复杂表格操作的场景下，表现优秀 https://tanstack.com/table/v8  和你文中所表述一致 

另外一篇文章讲什么是 headless 讲的也不错  https://www.merrickchristensen.com/articles/headless-user-interface-components/ ，这篇文章写的亮点是由浅入深地介绍了，什么是 headless 的组件设计模式，从最基础的代码开始，一直到如何封装
