### ISSUE TITLE
如何为 TS 类型写单测

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#446]
本周分享一下自己的工作经验，如何对针对 TS 类型写单测。

---

[如何为 TS 类型写单测](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/260.%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%A6%82%E4%BD%95%E4%B8%BA%20TS%20%E7%B1%BB%E5%9E%8B%E5%86%99%E5%8D%95%E6%B5%8B%E3%80%8B.md)

**Comment by rudy-xhd** [comment]
可以参考vue3源码的类型的测试
https://github.com/vuejs/core/blob/main/test-dts/index.d.ts

**Comment by waitingsong** [comment]
```
一种做法是直接访问类型提示，此时会出现错误下划线:

myLib.add
      ~~~ // Property 'add' does not exist on type MyLib
```
可以使用 `// @ts-expect-error`  这个（行前）注释来实现
1. 屏蔽类型错误提示
2. 如果后续这个属性（比如 .add）被开放了，那么就会出现类型异常（期望是有异常，但是因为这个属性被公开了不会有预期的异常，所以会提示异常）

如果采用 `// @ts-ignore` 这个注释，那么只能屏蔽异常，而不能在属性公开性变动后检测是否满足类型需求。
