### ISSUE TITLE
精读《Rest vs Spread 语法》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#447]
本周聊聊 [Rest vs Spread syntax in JavaScript](https://www.amitmerchant.com/rest-vs-spread-syntax-in-javascript/)，同时聊聊解构的坑。

---

[精读《Rest vs Spread 语法》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/261.%E7%B2%BE%E8%AF%BB%E3%80%8ARest%20vs%20Spread%20%E8%AF%AD%E6%B3%95%E3%80%8B.md)

**Comment by hua03** [comment]
```js
const obj = {
    a: 1,
    b: get() { return 2 }
}
const newObj = { ...obj }
```

这里举例的语法有错误

**Comment by ascoders** [comment]
@hua03 已修复：`get b() { return 2 }`
