### ISSUE TITLE
精读《迭代器 Iterable》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#448]
本周精读的文章是 [Iterables](https://javascript.info/iterable) 与 [Iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)，按照为什么需要迭代器、迭代器是如何设计的，我们还能怎么利用迭代器展开来讲。

---

[精读《迭代器 Iterable》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/262.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%BF%AD%E4%BB%A3%E5%99%A8%20Iterable%E3%80%8B.md)

**Comment by zq0904** [comment]
为什么 对象不具备迭代器 仍然可以使用展开运算 不能for of

示例
```ts
const obj = {}
const o = { ...obj }
```

**Comment by ascoders** [comment]
@zq0904 对象不支持 `[ ...obj ]`，这才是迭代器展开。

**Comment by KuangDaDa** [comment]
是不是 用 迭代器 实现 async/await 的吗？

**Comment by wangcongyi** [comment]
```js

const range = {
  from: 1,
  to: 5,

  [Symbol.iterator]() {
    this.current = this.from;
    return this;
  },

  next() {
    if (this.current <= this.to) {
      return { done: false, value: this.current++ };     //  <-----  this.current+1  或者其他运算
    } else {
      return { done: true };
    }
  },
};

[...range]; // [1, 2, 3, 4, 5]

```
上面的代码 我把  **this.current++** 改成  **this.current+1** 或者其他运算   
chrome 崩溃了 错误代码：Out of Memory。  
版本 107.0.5304.88（正式版本） （64 位）

这是为啥？  PS：怎么想chrome 提 issue， 是什么项目？

**Comment by HiWayne** [comment]
为什么对象可以支持for in，for in 不算迭代吗
