### ISSUE TITLE
精读《磁贴布局 - 功能分析》

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#458]
磁贴布局三部曲：功能分析、实现分析、性能优化

没有用 react-grid-layout，因为做了定制支持嵌套拖拽，以及可以和自由布局结合。原创无原文。

---

[精读《磁贴布局 - 功能分析》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/265.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%A3%81%E8%B4%B4%E5%B8%83%E5%B1%80%20-%20%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90%E3%80%8B.md)

**Comment by ascoders** [comment]
分三周更新，本周更新第一部分：功能分析。

**Comment by ascoders** [comment]
> 后续是否会考虑开源出磁贴布局的代码呢

暂不考虑，一般用还是考虑 react-grid-layout 吧，如果真有嵌套拖拽或者自由布局需求再考虑，一般开源场景没有这么深的定制。

**Comment by LiuL0703** [comment]
对比在编辑器里做这个只能做水平碰撞，情况复杂，十分麻烦。

**Comment by samwangdd** [comment]
能否分享一下实现思路？H5 搭建支持自由布局是个刚需

> > 后续是否会考虑开源出磁贴布局的代码呢
> 
> 暂不考虑，一般用还是考虑 react-grid-layout 吧，如果真有嵌套拖拽或者自由布局需求再考虑，一般开源场景没有这么深的定制。

**Comment by ascoders** [comment]
见这篇 [磁贴布局实现](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/266.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%A3%81%E8%B4%B4%E5%B8%83%E5%B1%80%20-%20%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0%E3%80%8B.md)

**Comment by samwangdd** [comment]
> 见这篇 [磁贴布局实现](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/266.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%A3%81%E8%B4%B4%E5%B8%83%E5%B1%80%20-%20%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0%E3%80%8B.md)

好像没有看出来有关于**嵌套拖拽或者自由布局** 的说明呢 🥲

**Comment by ascoders** [comment]
还没写完，最近精力主要在 gpt，后面会先追更几篇 gpt 的文章，然后再回到搭建
