### ISSUE TITLE
可视化搭建内置 API

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#467]
接着上篇，介绍可视化搭建内置的 API，包括提供的内置变量与方法。

---

[可视化搭建内置 API](https://github.com/ascoders/weekly/blob/master/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA/271.%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA%E5%86%85%E7%BD%AE%20API.md)

**Comment by tzstone** [comment]
关于 setProps/setComponent 的api有一点不解, callback的入参应该分别是对应组件的props和组件实例吧? 这样做的用意是让上层去决定怎么修改props和组件实例吗? 这样的话这两个api本身好像没做啥.

**Comment by ascoders** [comment]
@tzstone 就是如此，这个框架不参与业务逻辑，只提供通用函数，目标是统一接口和心智，让业务事半功倍。

我们实际用的话很少会直接调用底层 api，都是业务封装一个更有含义的方法，比如 updatePosition 修改组件位置等等，但这些函数背后的实现调用全是 setProps，维护同学看到这里就会心一笑，不用继续看下去了，整个业务代码背后逻辑也一下子就理顺了。
