### ISSUE TITLE
可视化搭建 - 定义联动协议

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#471]
定义了组件值与联动协议后，就可以在业务层使用这个框架，并定义业务层更好用的联动协议了。

---

[可视化搭建 - 定义联动协议](https://github.com/ascoders/weekly/blob/master/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA/274.%E5%AE%9A%E4%B9%89%E8%81%94%E5%8A%A8%E5%8D%8F%E8%AE%AE.md)

**Comment by bcguan2008** [comment]
🤩🤩🤩
