### ISSUE TITLE
可视化搭建 - 组件值校验

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#473]
[可视化搭建 - 组件值校验](https://github.com/ascoders/weekly/blob/master/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA/275.%E7%BB%84%E4%BB%B6%E5%80%BC%E6%A0%A1%E9%AA%8C.md)

**Comment by chenweihuan** [comment]
自定义校验规则不错👍  
顺便再问一下，有考虑过值相互依赖的场景吗？

**Comment by ascoders** [comment]
@chenweihuan 
- 如果没有成环，是支持的，就是框架实现代码要先分析依赖链条，从 0 依赖部分开始一步步执行。类似依赖注入的调用顺序逻辑。
- 如果成环了，比如 a 与 b 相互依赖，那逻辑上行不通，框架可以做兜底报错，而不要陷入死循环。

**Comment by bcguan2008** [comment]
这个值的校验描述的是 渲染时，而不是 设计时吧。 那么渲染时也会感知 ComponentMeta 么？设计时是否也会感知 ComponentMeta 呢
