### ISSUE TITLE
可视化搭建 - keepAlive 模式

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#475]
实现布局时，免不了产生跨越层级的拖动，keepAlive 模式要解决的问题，就是让组件移动到新父级时，不重新渲染。

---

[可视化搭建 - keepAlive 模式](https://github.com/ascoders/weekly/blob/master/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA/276.keepAlive%20%E6%A8%A1%E5%BC%8F.md)

**Comment by yanghuanrong** [comment]
这个思路非常惊奇。能给到很多启发

[createPortal](https://react.dev/reference/react-dom/createPortal) 可以将 React 实例渲染到任意指定 DOM 上，所以我们利用这个 API，将组件树的组件打平，但通过 createPortal 生成到嵌套的 DOM 树上，就同时实现了以下两点：

- 在 dom 结构上依然符合组件树的嵌套描述。
- 在 React 实例角度，没有嵌套关系。
