### ISSUE TITLE
可视化搭建 - 自动批处理与冻结

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#484]
[可视化搭建 - 自动批处理与冻结](https://github.com/ascoders/weekly/blob/master/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%90%AD%E5%BB%BA/279.%E8%87%AA%E5%8A%A8%E6%89%B9%E5%A4%84%E7%90%86%E4%B8%8E%E5%86%BB%E7%BB%93.md)

**Comment by Theonlyxia** [comment]
这是什么？没有说明？

**Comment by ascoders** [comment]
sorry，忘记写说明了，补充一下：

性能优化是可视化搭建不可或缺的部分，这次介绍自动批处理与冻结两种性能优化手段，让声明式框架在不过多侵入业务代码的情况下获得良好的性能。
