### ISSUE TITLE
这里我想是对应的 '*' 不匹配任何字符？

### ISSUE THREAD

**Issue by Mahoo12138** [ascoders/weekly#494]
https://github.com/ascoders/weekly/blob/77273b36f65c1d0b419085a181d9c6e680f5a97f/%E7%AE%97%E6%B3%95/283.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%AE%97%E6%B3%95%E9%A2%98%20-%20%E9%80%9A%E9%85%8D%E7%AC%A6%E5%8C%B9%E9%85%8D%E3%80%8B.md?plain=1#L32

**Comment by ascoders** [comment]
是的，手误，已修复
