### ISSUE TITLE
第二季准备开更，内容预告！

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#510]
花了小半年功夫学习了机器学习，毕竟大模型已经深入到我们工作，必须深入一波原理，吃一颗定心丸。

我的主要学习资料来自 [李宏毅老师](https://www.youtube.com/@HungyiLeeNTU)，强烈推荐给想接触一手资料的同学。

为了证明我有努力产生知识，而不是知识的搬运工，我会使用前端同学最为熟悉的 TS 从零开始实现神经网络架构，并且让它在浏览器跑起来。这样不仅可以让学习理解更深刻，还能让我们在生产环境使用 python 实现时，“退” 可直接调用现成库变成调参工程师，“进” 可创建新的思路优化神经网络架构。

### 第二季的目标

1. 从零开始构建牢固的机器学习基础。就如芯片用沙子制造一样，我们要从玩沙子开始，看着沙子如何一步步变成芯片。
2. 深度体会高大上的名词。比如卷积网络、自注意机制、监督学习、无监督学习、增强学习，当看到这些词，脑海里想的不只是这些词的时候，就入门了。
3. 写下来是为了快忘的时候，打开文章可以快速回忆起内容，所以我会努力给每篇文章一个好的头图用于概括通篇内容，以及知识点回忆。不是用来学习！学习要从沙子开始，而不是芯片开始。

### 第二季的更新节奏

这一季为了保证内容质量，与往期固定周更不同，采取不定期更新机制，但发布时间还是在周一（也许是一周，两周，或者三周才更新一次，但我不会鸽太久）。

### 这是要卖课的节奏吗

内容完全免费！真要卖课我会选择 HTML 入门作为主题 😂，写精读的意义在于我也可以持续学习，而不是面向新手反复写对我没有新认知的内容。

### 部分内容大纲

简单列了一些开头大纲，证明我真的是懂行的！

- 机器学习就是找函数（计算机只能进行函数运算，但函数可以很复杂）
    - 3 步！define function、define loss、optimization
    - 用最简单的线性函数为例
- 类神经网络 - 定义可以逼近一切的函数
    - Get 到机器学习与矩阵计算，GPU 的关系
- 类神经网络 - sigmoid、relu 等启动函数
- 类神经网络 - 使用反向传播优化

### 最后的话

我学习机器学习的动力来源于 ChatGPT，我相信所有人都想搞明白 ChatGPT 的原理，但直接看 Transformer 架构的介绍短片是没有用的，我相信没有人能真的看懂它们。想要真正搞懂 ChatGPT，必须从神经网络开始一步步入手，最后才能豁然领悟，这种体验在追求及时满足的社会里非常奢侈，这也是我希望给大家带来的核心价值之一。

**Comment by a243065157** [comment]
收到

**Comment by haitaodesign** [comment]
期待！

**Comment by jjeejj** [comment]
赞👍

**Comment by glows777** [comment]
期待😚

**Comment by Trojan0523** [comment]
非常期待

**Comment by wangrongding** [comment]
赞👍🏻非常期待

**Comment by zoro-r** [comment]
期待 咋订阅

**Comment by ascoders** [comment]
> 期待 咋订阅

Watch 此 repo 就行了，每次发文章会收到消息。第一篇文章已经发布了 [机器学习简介: 寻找函数的艺术](https://github.com/ascoders/weekly/blob/master/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/291.%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%AE%80%E4%BB%8B%3A%20%E5%AF%BB%E6%89%BE%E5%87%BD%E6%95%B0%E7%9A%84%E8%89%BA%E6%9C%AF.md)
