### ISSUE TITLE
反向传播: 揭秘神经网络的学习机制

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#513]
[反向传播: 揭秘神经网络的学习机制](https://github.com/ascoders/weekly/blob/master/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/294.%E5%8F%8D%E5%90%91%E4%BC%A0%E6%92%AD%3A%20%E6%8F%AD%E7%A7%98%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84%E5%AD%A6%E4%B9%A0%E6%9C%BA%E5%88%B6.md)

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。
