### ISSUE TITLE
完整实现神经网络: 实战演练

### ISSUE THREAD

**Issue by ascoders** [ascoders/weekly#516]
[完整实现神经网络: 实战演练](https://github.com/ascoders/weekly/blob/master/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/295.%E5%AE%8C%E6%95%B4%E5%AE%9E%E7%8E%B0%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%3A%20%E5%AE%9E%E6%88%98%E6%BC%94%E7%BB%83.md)

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。
